- hosts: localhost
  become: true
  vars:
    - apt_file_chrome: /etc/apt/sources.list.d/google-chrome.list
  pre_tasks:
    - name: Does the Google apt file exist?
      command: test -f {{apt_file_chrome}}
      register: google_apt_exists
      ignore_errors: True
    - name: Add Google Chrome key
      shell: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      when: google_apt_exists.rc == 1
    - name: Add Google Chrome repo
      copy: content="deb http://dl.google.com/linux/chrome/deb/ stable main" dest={{apt_file}} owner=root group=root mode=644
      when: google_apt_exists.rc == 1
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
  tasks:
    - include: tasks/users.yml
    - include: tasks/cron.yml
    - include: tasks/packages.yml
  roles:
    - common
    - role: gnome
      tags: ["gnome"]
      become: yes
      become_user: "{{ ansible_env.SUDO_USER }}"