- name: Install packages
  apt: name={{item}}
  with_items:
    - htop
    - mc
    - tmux
    - gnome-tweaks
    - steam
    - code
    - vlc
    - gnome-shell-extension-appindicator
    - google-chrome-stable