---
# roles/common/tasks/main.yml
# requires gsettings module

# - name: Install python-psutil package
#   apt: name=python-psutil

- name: Copy wallpaper file
  copy: src=files/wallpaper.jpg dest=/home/gillian/Pictures/wallpaper.jpg owner=gillian group=gillian mode=600

- name: Copy lockscreenfile
  copy: src=files/lockscreen.jpg dest=/home/gillian/Pictures/lockscreen.jpg owner=gillian group=gillian mode=600

- name: Change dconf settings
  dconf: key={{ item.value.key }}
    value={{ item.value.value }}
  with_dict: "{{ gsettings }}"
  ignore_errors: true
