---
# roles/common/tasks/main.yml

- name: Install apt packages
  apt: name={{item}} state=present
  with_items:
    - "{{ apt_packages }}"

- name: Install pip packages
  pip: name={{ item }} state=latest
  with_items:
    - "{{ pip_packages }}"

- name: NOPASSWD sudo
  lineinfile: "dest=/etc/sudoers.d/{{ ansible_env.SUDO_USER }}
    create=yes state=present mode=0440
    owner=root group=root
    line='{{ ansible_env.USERNAME }} ALL=(ALL) NOPASSWD: ALL'"

- include: chrome.yml
- include: vscode.yml

