---
# roles/common/tasks/main.yml

- name: Install apt packages
  apt: name={{item}} state=present
  with_items:
    - "{{ apt_packages }}"

- name: Uninstall unwanted packages
  apt: name={{item}} state=absent
  with_items:
    - "{{ unwanted_packages }}"

- name: Install pip packages
  pip: name={{ item }} state=latest
  with_items:
    - "{{ pip_packages }}"

- name: NOPASSWD sudo
  lineinfile: "dest=/etc/sudoers.d/gillian
    create=yes state=present mode=0440
    owner=root group=root
    line='gillian ALL=(ALL) NOPASSWD: ALL'"

- include: chrome.yml
- include: vscode.yml

